### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by clsferguson** [Michaelvilleneuve/lg-netcast-control#2]
Getting this error when i try npm start.

![error](https://user-images.githubusercontent.com/48876201/56226262-1ba4e980-6030-11e9-8b4c-e236c901c636.jpg)

**Comment by Michaelvilleneuve** [comment]
Hi, it’s seems to be related to Babel-cli, not directly to this project

**Comment by clsferguson** [comment]
i opened an issue on babel's github.

do you think a different version (older) of babel-cli may correct the issue? 

https://github.com/babel/babel/issues/9862

**Comment by clsferguson** [comment]
resolved the run time error. but now i get this error in the log.

$ npm start

> lg-control@1.0.0 start C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control
> nodemon --exec node ./node_modules/babel-cli/bin/babel-node.js --presets node6 ./app.js

[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./node_modules/babel-cli/bin/babel-node.js --presets node6 ./app.js`
C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "stage-3" relative to directory "C:\\Users\\cferg\\AppData\\Roaming\\npm\\node_modules\\lg-control"
    at C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:666:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Michaelvilleneuve** [comment]
Another babel error, you should consider upgrading all the Babel dependencies to recent ones, you may have noticed how old they are

**Comment by clsferguson** [comment]
is there an easy way to do that? lol. i'm still having issues

**Comment by clsferguson** [comment]
oh i got it working. To do so, from a fresh install of lg-netcast-control. I modified the start line in the package.json file as described above. Then while in the lg-control folder I had to run 

`npm install babel-preset-stage-3`

now it is listening on port 1234.

**Comment by clsferguson** [comment]
well after all that it returns "bad request" when i send a command.

**Comment by Michaelvilleneuve** [comment]
Did you managed to set the TV password ? When you start the server the password should pop up on the screen, allowing you to set it on the server settings.
Otherwise, are you sure it is a Netcast Lg TV ?

**Comment by clsferguson** [comment]
Yes it is. It is either a netcast 2.0 or maybe even 1.0. I confirmed the IP address on the TV and I can get web responses from a chrome browser. I have an app on my phone that does make the code pop up, but it is 6 letters not numbers. I used that code in the config.json just to be sure. The TV model is a 55lw6500-ua https://www.amazon.com/LG-Infinia-55LW6500-55-Inch-LED-LCD/dp/B004OVEVP6
